// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Incident
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject incidentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Incident";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MemberId("MemberId"),
		Category("Category"),
		OperatingSystem("OperatingSystem"),
		AffectedComponent("AffectedComponent"),
		Severity("Severity"),
		Fix("Fix"),
		Acknowledgement("Acknowledgement"),
		ReasonForNo("ReasonForNo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Incident(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Incident"));
	}

	protected Incident(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject incidentMendixObject)
	{
		if (incidentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Incident", incidentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Incident");

		this.incidentMendixObject = incidentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Incident.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Incident initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Incident.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Incident initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Incident(context, mendixObject);
	}

	public static myfirstmodule.proxies.Incident load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Incident.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Incident> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Incident> result = new java.util.ArrayList<myfirstmodule.proxies.Incident>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Incident" + xpathConstraint))
			result.add(myfirstmodule.proxies.Incident.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MemberId
	 */
	public final java.lang.String getMemberId()
	{
		return getMemberId(getContext());
	}

	/**
	 * @param context
	 * @return value of MemberId
	 */
	public final java.lang.String getMemberId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MemberId.toString());
	}

	/**
	 * Set value of MemberId
	 * @param memberid
	 */
	public final void setMemberId(java.lang.String memberid)
	{
		setMemberId(getContext(), memberid);
	}

	/**
	 * Set value of MemberId
	 * @param context
	 * @param memberid
	 */
	public final void setMemberId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String memberid)
	{
		getMendixObject().setValue(context, MemberNames.MemberId.toString(), memberid);
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final myfirstmodule.proxies.ENU_Category getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final myfirstmodule.proxies.ENU_Category getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Category.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.ENU_Category.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(myfirstmodule.proxies.ENU_Category category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENU_Category category)
	{
		if (category != null)
			getMendixObject().setValue(context, MemberNames.Category.toString(), category.toString());
		else
			getMendixObject().setValue(context, MemberNames.Category.toString(), null);
	}

	/**
	 * @return value of OperatingSystem
	 */
	public final java.lang.String getOperatingSystem()
	{
		return getOperatingSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of OperatingSystem
	 */
	public final java.lang.String getOperatingSystem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OperatingSystem.toString());
	}

	/**
	 * Set value of OperatingSystem
	 * @param operatingsystem
	 */
	public final void setOperatingSystem(java.lang.String operatingsystem)
	{
		setOperatingSystem(getContext(), operatingsystem);
	}

	/**
	 * Set value of OperatingSystem
	 * @param context
	 * @param operatingsystem
	 */
	public final void setOperatingSystem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operatingsystem)
	{
		getMendixObject().setValue(context, MemberNames.OperatingSystem.toString(), operatingsystem);
	}

	/**
	 * @return value of AffectedComponent
	 */
	public final java.lang.String getAffectedComponent()
	{
		return getAffectedComponent(getContext());
	}

	/**
	 * @param context
	 * @return value of AffectedComponent
	 */
	public final java.lang.String getAffectedComponent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AffectedComponent.toString());
	}

	/**
	 * Set value of AffectedComponent
	 * @param affectedcomponent
	 */
	public final void setAffectedComponent(java.lang.String affectedcomponent)
	{
		setAffectedComponent(getContext(), affectedcomponent);
	}

	/**
	 * Set value of AffectedComponent
	 * @param context
	 * @param affectedcomponent
	 */
	public final void setAffectedComponent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String affectedcomponent)
	{
		getMendixObject().setValue(context, MemberNames.AffectedComponent.toString(), affectedcomponent);
	}

	/**
	 * Set value of Severity
	 * @param severity
	 */
	public final myfirstmodule.proxies.ENU_Severity getSeverity()
	{
		return getSeverity(getContext());
	}

	/**
	 * @param context
	 * @return value of Severity
	 */
	public final myfirstmodule.proxies.ENU_Severity getSeverity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Severity.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.ENU_Severity.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Severity
	 * @param severity
	 */
	public final void setSeverity(myfirstmodule.proxies.ENU_Severity severity)
	{
		setSeverity(getContext(), severity);
	}

	/**
	 * Set value of Severity
	 * @param context
	 * @param severity
	 */
	public final void setSeverity(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENU_Severity severity)
	{
		if (severity != null)
			getMendixObject().setValue(context, MemberNames.Severity.toString(), severity.toString());
		else
			getMendixObject().setValue(context, MemberNames.Severity.toString(), null);
	}

	/**
	 * @return value of Fix
	 */
	public final java.lang.String getFix()
	{
		return getFix(getContext());
	}

	/**
	 * @param context
	 * @return value of Fix
	 */
	public final java.lang.String getFix(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Fix.toString());
	}

	/**
	 * Set value of Fix
	 * @param fix
	 */
	public final void setFix(java.lang.String fix)
	{
		setFix(getContext(), fix);
	}

	/**
	 * Set value of Fix
	 * @param context
	 * @param fix
	 */
	public final void setFix(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fix)
	{
		getMendixObject().setValue(context, MemberNames.Fix.toString(), fix);
	}

	/**
	 * Set value of Acknowledgement
	 * @param acknowledgement
	 */
	public final myfirstmodule.proxies.ENU_Acknowledgement getAcknowledgement()
	{
		return getAcknowledgement(getContext());
	}

	/**
	 * @param context
	 * @return value of Acknowledgement
	 */
	public final myfirstmodule.proxies.ENU_Acknowledgement getAcknowledgement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Acknowledgement.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.ENU_Acknowledgement.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Acknowledgement
	 * @param acknowledgement
	 */
	public final void setAcknowledgement(myfirstmodule.proxies.ENU_Acknowledgement acknowledgement)
	{
		setAcknowledgement(getContext(), acknowledgement);
	}

	/**
	 * Set value of Acknowledgement
	 * @param context
	 * @param acknowledgement
	 */
	public final void setAcknowledgement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENU_Acknowledgement acknowledgement)
	{
		if (acknowledgement != null)
			getMendixObject().setValue(context, MemberNames.Acknowledgement.toString(), acknowledgement.toString());
		else
			getMendixObject().setValue(context, MemberNames.Acknowledgement.toString(), null);
	}

	/**
	 * @return value of ReasonForNo
	 */
	public final java.lang.String getReasonForNo()
	{
		return getReasonForNo(getContext());
	}

	/**
	 * @param context
	 * @return value of ReasonForNo
	 */
	public final java.lang.String getReasonForNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReasonForNo.toString());
	}

	/**
	 * Set value of ReasonForNo
	 * @param reasonforno
	 */
	public final void setReasonForNo(java.lang.String reasonforno)
	{
		setReasonForNo(getContext(), reasonforno);
	}

	/**
	 * Set value of ReasonForNo
	 * @param context
	 * @param reasonforno
	 */
	public final void setReasonForNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reasonforno)
	{
		getMendixObject().setValue(context, MemberNames.ReasonForNo.toString(), reasonforno);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return incidentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Incident that = (myfirstmodule.proxies.Incident) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Incident";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
